DROP TABLE IF EXISTS auser;

CREATE TABLE auser
(
    id BIGINT(20) NOT NULL COMMENT '主键ID',
    name VARCHAR(30) NULL DEFAULT NULL COMMENT '姓名',
    age INT(11) NULL DEFAULT NULL COMMENT '年龄',
    email VARCHAR(50) NULL DEFAULT NULL COMMENT '邮箱',
    PRIMARY KEY (id)
);


DROP TABLE IF EXISTS gps_info;

CREATE TABLE gps_info
(
    id int(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
    lat DECIMAL(10,6) NULL DEFAULT NULL COMMENT '经度',
    lon DECIMAL(10,6) NULL DEFAULT NULL COMMENT '纬度',
    update_time datetime(0) NULL DEFAULT NULL COMMENT '更新时间',
    PRIMARY KEY (id)
)

